/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart */
        get: operations["chart_chart__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quote/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote */
        get: operations["quote_quote__symbol__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/crypto/{base}/{quote_ccy}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Crypto */
        get: operations["crypto_crypto__base___quote_ccy__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yield Curve */
        get: operations["yield_curve_yield_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News */
        get: operations["news_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feeds */
        get: operations["list_feeds_news_feeds_get"];
        put?: never;
        /** Add Feed */
        post: operations["add_feed_news_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** People Feed */
        post: operations["people_feed_people_feed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFeedRequest */
        AddFeedRequest: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** Balance */
        Balance: {
            /** Asset */
            asset: string;
            /** Total */
            total: number;
            /** Available */
            available: number;
            /** Source */
            source: string;
        };
        /**
         * CalendarResponse
         * @description `cal` command. Stubbed in early phases (status = not_implemented).
         */
        CalendarResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
        };
        /** Candle */
        Candle: {
            /** T */
            t: number;
            /** O */
            o: number;
            /** H */
            h: number;
            /** L */
            l: number;
            /** C */
            c: number;
            /** V */
            v: number;
        };
        /** CandlesResponse */
        CandlesResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Symbol */
            symbol: string;
            /** Source */
            source: string;
            /**
             * Candles
             * @default []
             */
            candles: components["schemas"]["Candle"][];
        };
        /** CryptoResponse */
        CryptoResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Pair */
            pair: string;
            /** Source */
            source: string;
            quote?: components["schemas"]["Quote"] | null;
            /**
             * Candles
             * @default []
             */
            candles: components["schemas"]["Candle"][];
        };
        /** FeedError */
        FeedError: {
            /** Person */
            person: string;
            /** Message */
            message: string;
        };
        /** FeedInfo */
        FeedInfo: {
            /** Name */
            name: string;
            /**
             * Urls
             * @default []
             */
            urls: string[];
        };
        /** FeedListResponse */
        FeedListResponse: {
            status: components["schemas"]["SourceStatus"];
            /**
             * Feeds
             * @default []
             */
            feeds: components["schemas"]["FeedInfo"][];
        };
        /** FollowItem */
        FollowItem: {
            /** Person */
            person: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Url */
            url: string;
            /** Publishedts */
            publishedTs?: number | null;
            /** Source */
            source: string;
            /** Kind */
            kind: string;
            /** Publisher */
            publisher?: string | null;
            /**
             * Primary
             * @default false
             */
            primary: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response shape for GET /health.
         *
         *     Pydantic models are the single source of truth for response shapes
         *     (CLAUDE.md type contract); the frontend types are generated from this.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Url */
            url: string;
            /** Publishedts */
            publishedTs?: number | null;
            /** Feed */
            feed: string;
        };
        /** NewsResponse */
        NewsResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Feed */
            feed?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["NewsItem"][];
        };
        /** PeopleFeedRequest */
        PeopleFeedRequest: {
            /**
             * People
             * @default []
             */
            people: components["schemas"]["PersonRef"][];
            /**
             * Limitperperson
             * @default 25
             */
            limitPerPerson: number;
        };
        /** PeopleFeedResponse */
        PeopleFeedResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["FollowItem"][];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FeedError"][];
        };
        /** PersonRef */
        PersonRef: {
            /** Name */
            name: string;
            /**
             * Feeds
             * @default []
             */
            feeds: string[];
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Positions
             * @default []
             */
            positions: components["schemas"]["Position"][];
            /**
             * Balances
             * @default []
             */
            balances: components["schemas"]["Balance"][];
        };
        /** Position */
        Position: {
            /** Symbol */
            symbol: string;
            /** Qty */
            qty: number;
            /** Avgcost */
            avgCost: number;
            /** Marketvalue */
            marketValue: number;
            /** Unrealizedpnl */
            unrealizedPnl: number;
            /** Source */
            source: string;
        };
        /** Quote */
        Quote: {
            /** Symbol */
            symbol: string;
            /** Last */
            last?: number | null;
            /** Bid */
            bid?: number | null;
            /** Ask */
            ask?: number | null;
            /** Change */
            change?: number | null;
            /** Changepct */
            changePct?: number | null;
            /** Ts */
            ts?: number | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Source */
            source: string;
        };
        /** QuoteResponse */
        QuoteResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            quote?: components["schemas"]["Quote"] | null;
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "ok" | "empty" | "source_down" | "unauthenticated" | "rate_limited" | "not_implemented";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YieldCurveResponse */
        YieldCurveResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["YieldPoint"][];
        };
        /** YieldPoint */
        YieldPoint: {
            /** Tenorlabel */
            tenorLabel: string;
            /** Tenoryears */
            tenorYears: number;
            /** Ratepct */
            ratePct: number;
            /** Obsdate */
            obsDate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chart_chart__symbol__get: {
        parameters: {
            query?: {
                interval?: string;
            };
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_quote__symbol__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crypto_crypto__base___quote_ccy__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                base: string;
                quote_ccy: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CryptoResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    yield_curve_yield_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldCurveResponse"];
                };
            };
        };
    };
    news_news_get: {
        parameters: {
            query?: {
                feed?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feeds_news_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
        };
    };
    add_feed_news_feeds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_feed_people_feed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeopleFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
        };
    };
}
