/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chart */
        get: operations["chart_chart_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quote": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quote */
        get: operations["quote_quote_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Portfolio */
        get: operations["portfolio_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/yield": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Yield Curve */
        get: operations["yield_curve_yield_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/swaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Swaps */
        get: operations["swaps_swaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** News */
        get: operations["news_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Feeds */
        get: operations["list_feeds_news_feeds_get"];
        put?: never;
        /** Add Feed */
        post: operations["add_feed_news_feeds_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * News Catalog
         * @description Curated, off-by-default sources the user can enable from the News picker.
         */
        get: operations["news_catalog_news_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/sources/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable Source */
        post: operations["enable_source_news_sources_enable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/news/sources/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable Source */
        post: operations["disable_source_news_sources_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/people/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** People Feed */
        post: operations["people_feed_people_feed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar */
        get: operations["calendar_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Keys
         * @description Local-first key entry (localhost only): write the supplied non-empty keys
         *     into api/.env and hot-reload settings. Returns the refreshed status only —
         *     key VALUES are never returned to the browser.
         */
        post: operations["update_keys_status_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ibkr/auth": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ibkr Auth */
        get: operations["ibkr_auth_ibkr_auth_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFeedRequest */
        AddFeedRequest: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /**
         * AsOfCurve
         * @description A yield curve as of one observation date (latest, a relative lookback, or
         *     an exact calendar date). `obs_date` is the most recent per-tenor observation
         *     actually used; `requested_date` is the target as-of date.
         */
        AsOfCurve: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Requesteddate */
            requestedDate: number;
            /** Obsdate */
            obsDate: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["YieldPoint"][];
        };
        /** Balance */
        Balance: {
            /** Asset */
            asset: string;
            /** Total */
            total: number;
            /** Available */
            available: number;
            /** Source */
            source: string;
        };
        /**
         * CalendarResponse
         * @description `cal` command. Stubbed in early phases (status = not_implemented).
         */
        CalendarResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
        };
        /** Candle */
        Candle: {
            /** T */
            t: number;
            /** O */
            o: number;
            /** H */
            h: number;
            /** L */
            l: number;
            /** C */
            c: number;
            /** V */
            v: number;
        };
        /** CandlesResponse */
        CandlesResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Symbol */
            symbol: string;
            /** Source */
            source: string;
            /**
             * Candles
             * @default []
             */
            candles: components["schemas"]["Candle"][];
            /** @default 1h */
            interval: components["schemas"]["Interval"];
            /** @default 1M */
            span: components["schemas"]["Span"];
        };
        /** CatalogResponse */
        CatalogResponse: {
            status: components["schemas"]["SourceStatus"];
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SuggestedSource"][];
        };
        /** FeedError */
        FeedError: {
            /** Person */
            person: string;
            /** Message */
            message: string;
        };
        /** FeedInfo */
        FeedInfo: {
            /** Name */
            name: string;
            /**
             * Urls
             * @default []
             */
            urls: string[];
        };
        /** FeedListResponse */
        FeedListResponse: {
            status: components["schemas"]["SourceStatus"];
            /**
             * Feeds
             * @default []
             */
            feeds: components["schemas"]["FeedInfo"][];
        };
        /** FollowItem */
        FollowItem: {
            /** Person */
            person: string;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Url */
            url: string;
            /** Publishedts */
            publishedTs?: number | null;
            /** Source */
            source: string;
            /** Kind */
            kind: string;
            /** Publisher */
            publisher?: string | null;
            /**
             * Primary
             * @default false
             */
            primary: boolean;
            /**
             * Relevant
             * @default false
             */
            relevant: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Response shape for GET /health.
         *
         *     Pydantic models are the single source of truth for response shapes
         *     (CLAUDE.md type contract); the frontend types are generated from this.
         */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** IbkrAuthResponse */
        IbkrAuthResponse: {
            /**
             * State
             * @enum {string}
             */
            state: "authenticated" | "unauthenticated" | "unreachable";
            /** Loginurl */
            loginUrl: string;
            /** Detail */
            detail: string;
        };
        /**
         * Interval
         * @description Candle size (bar granularity).
         * @enum {string}
         */
        Interval: "1m" | "5m" | "15m" | "1h" | "4h" | "1d" | "1w";
        /** KeysUpdateRequest */
        KeysUpdateRequest: {
            /** Fredapikey */
            fredApiKey?: string | null;
            /** Krakenapikey */
            krakenApiKey?: string | null;
            /** Krakenapisecret */
            krakenApiSecret?: string | null;
        };
        /** MarginSummary */
        MarginSummary: {
            /** Equity */
            equity: number;
            /** Usedmargin */
            usedMargin: number;
            /** Freemargin */
            freeMargin: number;
            /** Marginlevel */
            marginLevel?: number | null;
            /** Unrealizedpnl */
            unrealizedPnl: number;
            /** Costbasis */
            costBasis: number;
            /** Valuation */
            valuation: number;
            /**
             * Source
             * @default kraken
             */
            source: string;
        };
        /** NewsItem */
        NewsItem: {
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /** Url */
            url: string;
            /** Publishedts */
            publishedTs?: number | null;
            /** Feed */
            feed: string;
        };
        /** NewsResponse */
        NewsResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Feed */
            feed?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["NewsItem"][];
        };
        /** PeopleFeedRequest */
        PeopleFeedRequest: {
            /**
             * People
             * @default []
             */
            people: components["schemas"]["PersonRef"][];
            /**
             * Limitperperson
             * @default 25
             */
            limitPerPerson: number;
        };
        /** PeopleFeedResponse */
        PeopleFeedResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Items
             * @default []
             */
            items: components["schemas"]["FollowItem"][];
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["FeedError"][];
        };
        /** PersonRef */
        PersonRef: {
            /** Name */
            name: string;
            /**
             * Feeds
             * @default []
             */
            feeds: string[];
        };
        /** PortfolioResponse */
        PortfolioResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Positions
             * @default []
             */
            positions: components["schemas"]["Position"][];
            /**
             * Balances
             * @default []
             */
            balances: components["schemas"]["Balance"][];
            marginSummary?: components["schemas"]["MarginSummary"] | null;
        };
        /** Position */
        Position: {
            /** Symbol */
            symbol: string;
            /** Qty */
            qty: number;
            /** Avgcost */
            avgCost: number;
            /** Marketvalue */
            marketValue: number;
            /** Unrealizedpnl */
            unrealizedPnl: number;
            /** Source */
            source: string;
            /** Side */
            side?: string | null;
            /** Marginused */
            marginUsed?: number | null;
        };
        /** Quote */
        Quote: {
            /** Symbol */
            symbol: string;
            /** Last */
            last?: number | null;
            /** Bid */
            bid?: number | null;
            /** Ask */
            ask?: number | null;
            /** Change */
            change?: number | null;
            /** Changepct */
            changePct?: number | null;
            /** Ts */
            ts?: number | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /** Source */
            source: string;
        };
        /** QuoteResponse */
        QuoteResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            quote?: components["schemas"]["Quote"] | null;
        };
        /** SourceConnection */
        SourceConnection: {
            /** Source */
            source: string;
            /** Configured */
            configured: boolean;
            /** Detail */
            detail: string;
        };
        /** SourceNameRequest */
        SourceNameRequest: {
            /** Name */
            name: string;
        };
        /**
         * SourceStatus
         * @enum {string}
         */
        SourceStatus: "ok" | "empty" | "source_down" | "unauthenticated" | "rate_limited" | "not_implemented";
        /**
         * Span
         * @description Chart lookback window.
         * @enum {string}
         */
        Span: "1D" | "5D" | "1M" | "3M" | "1Y" | "5Y";
        /** StatusResponse */
        StatusResponse: {
            /**
             * Sources
             * @default []
             */
            sources: components["schemas"]["SourceConnection"][];
        };
        /** SuggestedSource */
        SuggestedSource: {
            /** Name */
            name: string;
            /** Category */
            category: string;
            /**
             * Urls
             * @default []
             */
            urls: string[];
        };
        /**
         * SwapCurve
         * @description SOFR or US CPI swap rates by tenor, as of one EOD SDR file.
         */
        SwapCurve: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Obsdate */
            obsDate: number;
            /**
             * Points
             * @default []
             */
            points: components["schemas"]["SwapTenorPoint"][];
        };
        /**
         * SwapTenorPoint
         * @description One standard tenor's summary from a day of SDR swap prints: the median
         *     fixed rate, how many prints fell in the bucket, and their summed notional.
         */
        SwapTenorPoint: {
            /** Tenorlabel */
            tenorLabel: string;
            /** Tenoryears */
            tenorYears: number;
            /** Ratepct */
            ratePct: number;
            /** Tradecount */
            tradeCount: number;
            /** Totalnotional */
            totalNotional: number;
        };
        /** SwapsResponse */
        SwapsResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /** Filedate */
            fileDate?: number | null;
            /**
             * Curves
             * @default []
             */
            curves: components["schemas"]["SwapCurve"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** YieldCurveResponse */
        YieldCurveResponse: {
            status: components["schemas"]["SourceStatus"];
            /** Message */
            message?: string | null;
            /**
             * Curves
             * @default []
             */
            curves: components["schemas"]["AsOfCurve"][];
        };
        /** YieldPoint */
        YieldPoint: {
            /** Tenorlabel */
            tenorLabel: string;
            /** Tenoryears */
            tenorYears: number;
            /** Ratepct */
            ratePct: number;
            /** Obsdate */
            obsDate: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    chart_chart_get: {
        parameters: {
            query: {
                symbol: string;
                interval?: components["schemas"]["Interval"];
                span?: components["schemas"]["Span"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandlesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    quote_quote_get: {
        parameters: {
            query: {
                symbol: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuoteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioResponse"];
                };
            };
        };
    };
    yield_curve_yield_get: {
        parameters: {
            query?: {
                asof?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["YieldCurveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    swaps_swaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SwapsResponse"];
                };
            };
        };
    };
    news_news_get: {
        parameters: {
            query?: {
                feed?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_feeds_news_feeds_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
        };
    };
    add_feed_news_feeds_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    news_catalog_news_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    enable_source_news_sources_enable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_source_news_sources_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceNameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeedListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    people_feed_people_feed_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PeopleFeedRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeopleFeedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_calendar_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarResponse"];
                };
            };
        };
    };
    status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    update_keys_status_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeysUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ibkr_auth_ibkr_auth_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IbkrAuthResponse"];
                };
            };
        };
    };
}
